### ISSUE TITLE
Flaky/frequent "fetch failed" errors

### ISSUE THREAD

**Issue by reececomo** [FedericoCarboni/setup-ffmpeg#28]
Hello, thanks for the GitHub action. Unfortunately about 1 in 3 builds fails with "fetch failed":

![Image](https://github.com/user-attachments/assets/656e7303-10a4-4d8a-bdeb-40ebc92a884b)

I realise this is a duplicate of #20 but its still occurring in May 2025

```yaml
      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          ffmpeg-version: 7.0.1
```

**Comment by reececomo** [comment]
It usually works fine on re-run. Any chance we could add automatic retry x 3 to this action or something? Its the only action that fails in our long build & deploy pipeline.

**Comment by buildgreatthings** [comment]
I plus one this.

**Comment by reececomo** [comment]
We also use a cache step already, so maybe the step could even check if  `ffmpeg-version` is installed and skip any fetching - that would cover ~99% of builds.

We can probably do that manually with shell scripts and conditional steps already so no big deal if not 👍

**Comment by reececomo** [comment]
It seems like upstream just has very aggressive rate limiting in place.

Here's a composite step that uses **exponential backoff** (max: 30 seconds) with 10 retries. Should be enough to wait out the rate limit on builds that fail to restore a cached version.

```yml
# .github/actions/install-ffmpeg/action.yml

name: install-ffmpeg
description: Installs ffmpeg with caching and aggressive retries.

runs:
  using: composite

  steps:
    - id: restore-cache
      uses: actions/cache/restore@v4
      with:
        key: ffmpeg-${{ hashFiles('.github/actions/install-ffmpeg/action.yml') }}
        path: $HOME/.ffmpeg

    - if: steps.restore-cache.outputs.cache-hit != 'true'
      name: download ffmpeg
      shell: bash
      run: |
        URL="https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz"
        MAX_RETRY_DELAY=30

        mkdir -p "$HOME/.ffmpeg"

        for i in {1..10}
        do
          echo "downloading ffmpeg (attempt: #$i)"

          if curl --connect-timeout 10 -vL "$URL" -o ffmpeg.tar.xz \
            && tar -xf ffmpeg.tar.xz --strip-components=1 -C "$HOME/.ffmpeg" \
            && rm ffmpeg.tar.xz; then
            echo "✅ ffmpeg installed successfully"
            exit 0
          fi

          [[ $i -ge 10 ]] && break

          retry_delay=$((2 ** i))
          [[ $retry_delay -gt $MAX_RETRY_DELAY ]] && retry_delay=$MAX_RETRY_DELAY
          echo "retrying in ${retry_delay}s..." && sleep $retry_delay
        done

        echo "❌ failed to install ffmpeg" >&2 \
          && exit 1

    - name: add ffmpeg to PATH
      shell: bash
      run: |
        export PATH="$HOME/.ffmpeg:$PATH"
        echo "$HOME/.ffmpeg" >> $GITHUB_PATH
        ffmpeg -version

    - uses: actions/cache/save@v4
      with:
        key: ffmpeg-${{ hashFiles('.github/actions/install-ffmpeg/action.yml') }}
        path: $HOME/.ffmpeg
```

Replace `URL` with desired build url.

#### Usage in workflow:

```yml
jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-ffmpeg
      # ...
```

**Comment by yamatt** [comment]
> It seems like upstream just has very aggressive rate limiting in place.

That makes sense to me. When I started using this action it worked the first time, then just error'd after that.

I looked to fork the repo, but I would have to find another source of ffmpeg builds.

In the end did similar to yourself and made my own solution using the [jrottenberg/ffmpeg](https://github.com/jrottenberg/ffmpeg) docker image

My workflow now looks like this:

```yml
jobs:
  record:
    name: Record a Stream
    runs-on: ubuntu-24.04
    steps:
      - name: Stream to file
        run: |
          docker run --rm \
            -v "$PWD":/data \
            ghcr.io/jrottenberg/ffmpeg:7.1-alpine \
            -i '${{ inputs.url }}' -t '${{ inputs.duration }}' -f mp3 /data/output.mp3
      - name: Add file to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.id }}
          path: output.mp3
```
