### ISSUE TITLE
All runs fails with Error: TypeError: fetch failed

### ISSUE THREAD

**Issue by GillesJ** [FedericoCarboni/setup-ffmpeg#29]
```
0s
Run FedericoCarboni/setup-ffmpeg@v3.1
  with:
    ffmpeg-version: release
    linking-type: static
    github-token: ***
Error: TypeError: fetch failed
```

```
- name: Install FFmpeg for audio processing tests
  uses: FedericoCarboni/setup-ffmpeg@v3.1
  with:
    ffmpeg-version: release
```

Likely that fetching the external build or other resource is failing.

**Comment by Garfield-fr** [comment]
I have the same problem on my project.

Any news about that ?
Thanks

**Comment by Colk-tech** [comment]
I'm experiencing the same issue. It doesn't occur every time, but I occasionally encounter the error!

**Comment by yimejky** [comment]
We had the same problem in our CI and after x failed runs I decided to save you guys 😄 

Check releases https://www.johnvansickle.com/ffmpeg/old-releases/

```yaml
      - name: Load cached FFmpeg
        id: cache-ffmpeg
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/ffmpeg
            /usr/local/bin/ffprobe
          key: ${{ runner.os }}-ffmpeg-5.1.1

      - name: Install FFmpeg if not cached
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          VERSION=5.1.1
          RELEASE_NAME=ffmpeg-${VERSION}-amd64-static
          wget --timeout=8 --tries=30 https://www.johnvansickle.com/ffmpeg/old-releases/${RELEASE_NAME}.tar.xz
          tar -xf ${RELEASE_NAME}.tar.xz
          mv ${RELEASE_NAME}/ffmpeg ${RELEASE_NAME}/ffprobe /usr/local/bin/
          rm -rf ${RELEASE_NAME}
```
